[package]
name = "sprue-model"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
test-util = ["nanoid", "tokio"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
nanoid = { workspace = true, optional = true }
newtype-uuid = { workspace = true }
partial-struct = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }
v-api-installer = { workspace = true }
