[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
name = "oxvm_api"
path = "src/lib.rs"

[[bin]]
name = "oxvm-server"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
attest-data = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
const-oid = { workspace = true }
config = { workspace = true }
dice-verifier = { workspace = true }
dropshot = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hubpack = { workspace = true }
jsonwebtoken = { workspace = true }
model = { path = "../model" }
newtype-uuid = { workspace = true }
rsa = { workspace = true }
rustls = { workspace = true }
schemars = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
slog = { workspace = true }
slog-async = { workspace = true }
tap = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-slog = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
v-api = { workspace = true }
v-api-param = { workspace = true }
vm-attest = { workspace = true }
x509-cert = { workspace = true }
